# Use the official Node 18.0 image as a base image
FROM node:18.0

#  Set the working directory
WORKDIR /app

# Copy the package file and install dependencies
COPY package.json /app/
RUN npm install

# Copy the rest of the application code
COPY . /app/

# Run the application
CMD ["npm", "run", "start"]