# Use the official Node 18.18.0 image as a base image
FROM node:18.18.0

# Install create-react-app globally
RUN npm install -g create-react-app

#  Set the working directory
WORKDIR /usr/src/app

# Copy the package file and install dependencies
COPY package.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Run the application
CMD ["npm", "run", "start"]
