# Generated by Django 4.0.5 on 2023-06-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('VA', 'Video + Audio'), ('A', 'Audio'), ('T', 'Transcript'), ('ETC', 'Others')], max_length=3)),
                ('reason_for_visit', models.CharField(choices=[('PC', 'Primary Care'), ('GC', 'Genetics Consult'), ('O', 'Other')], max_length=2)),
                ('sentiment', models.CharField(choices=[('P', 'Positive'), ('N', 'Negative'), ('NE', 'Neutral')], max_length=2)),
                ('patient_age_category', models.CharField(choices=[('C', 'Child'), ('A', 'Adolescent'), ('AD', 'Adult'), ('S', 'Senior')], max_length=2)),
            ],
        ),
    ]
