# Generated by Django 4.0.5 on 2023-06-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='data_source',
            field=models.CharField(choices=[('SI', 'Simulated'), ('SY', 'Synthesized'), ('R', 'Real Patient/Real Doctor')], default='R', max_length=2),
            preserve_default=False,
        ),
    ]
